"""cambio de cabecera tamaño de sin limite a 40 caracteres

Revision ID: 10c5ad27cc5e
Revises: c6f12c8b5c8b
Create Date: 2026-02-27 14:49:27.915059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10c5ad27cc5e'
down_revision: Union[str, Sequence[str], None] = 'c6f12c8b5c8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('COCHES_CABECERA', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_COCHES_CABECERA_Cabecera'), ['Cabecera'], unique=False)

    with op.batch_alter_table('CONSUMO_DESVIACION_INDICES', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_CONSUMO_DESVIACION_INDICES_Cabecera'), ['Cabecera'], unique=False)

    with op.batch_alter_table('CONSUMO_INDICE', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_CONSUMO_INDICE_Cabecera'), ['Cabecera'], unique=False)

    with op.batch_alter_table('CONSUMO_OBLIGATORIO', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_CONSUMO_OBLIGATORIO_Cabecera'), ['Cabecera'], unique=False)

    with op.batch_alter_table('GARANTIAS_CONSUMO', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_GARANTIAS_CONSUMO_Cabecera'), ['Cabecera'], unique=False)

    with op.batch_alter_table('GARANTIAS_FALLA', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_GARANTIAS_FALLA_Cabecera'), ['Cabecera'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GARANTIAS_FALLA', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_GARANTIAS_FALLA_Cabecera'))

    with op.batch_alter_table('GARANTIAS_CONSUMO', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_GARANTIAS_CONSUMO_Cabecera'))

    with op.batch_alter_table('CONSUMO_OBLIGATORIO', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_CONSUMO_OBLIGATORIO_Cabecera'))

    with op.batch_alter_table('CONSUMO_INDICE', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_CONSUMO_INDICE_Cabecera'))

    with op.batch_alter_table('CONSUMO_DESVIACION_INDICES', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_CONSUMO_DESVIACION_INDICES_Cabecera'))

    with op.batch_alter_table('COCHES_CABECERA', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_COCHES_CABECERA_Cabecera'))

    # ### end Alembic commands ###
