"""add: nuevo parque movil y cambio de float a Decimal(10,2)

Revision ID: 2551e9cd0e4b
Revises: 64815f746bd3
Create Date: 2026-07-02 19:25:09.956237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2551e9cd0e4b'
down_revision: Union[str, Sequence[str], None] = '64815f746bd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CARROCERIA',
    sa.Column('IDCarroceria', sa.Integer(), nullable=False),
    sa.Column('Marca', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('IDCarroceria')
    )
    op.create_table('CHASIS_MARCA',
    sa.Column('IDChasisMarca', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('IDChasisMarca'),
    sa.UniqueConstraint('Nombre')
    )
    op.create_table('MOTOR_MARCA',
    sa.Column('IDMotorMarca', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('IDMotorMarca'),
    sa.UniqueConstraint('Nombre')
    )
    op.create_table('CHASIS_MODELO',
    sa.Column('IDChasisModelo', sa.Integer(), nullable=False),
    sa.Column('IDChasisMarca', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['IDChasisMarca'], ['CHASIS_MARCA.IDChasisMarca'], ),
    sa.PrimaryKeyConstraint('IDChasisModelo'),
    sa.UniqueConstraint('IDChasisMarca', 'Nombre', name='unique_chasis_marca_modelo')
    )
    op.create_table('MOTOR_MODELO',
    sa.Column('IDMotorModelo', sa.Integer(), nullable=False),
    sa.Column('IDMotorMarca', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['IDMotorMarca'], ['MOTOR_MARCA.IDMotorMarca'], ),
    sa.PrimaryKeyConstraint('IDMotorModelo'),
    sa.UniqueConstraint('IDMotorMarca', 'Nombre', name='unique_motor_marca_modelo')
    )
    op.create_table('CHASIS',
    sa.Column('IDChasis', sa.Integer(), nullable=False),
    sa.Column('IDChasisModelo', sa.Integer(), nullable=False),
    sa.Column('ChasisCodigo', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['IDChasisModelo'], ['CHASIS_MODELO.IDChasisModelo'], ),
    sa.PrimaryKeyConstraint('IDChasis'),
    sa.UniqueConstraint('ChasisCodigo')
    )
    op.create_table('MOTOR',
    sa.Column('IDMotor', sa.Integer(), nullable=False),
    sa.Column('IDMotorModelo', sa.Integer(), nullable=False),
    sa.Column('MotorCodigo', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['IDMotorModelo'], ['MOTOR_MODELO.IDMotorModelo'], ),
    sa.PrimaryKeyConstraint('IDMotor'),
    sa.UniqueConstraint('MotorCodigo')
    )
    op.create_table('PARQUE_MOVIL',
    sa.Column('IDParqueMovil', sa.Integer(), nullable=False),
    sa.Column('IDChasis', sa.Integer(), nullable=False),
    sa.Column('IDMotor', sa.Integer(), nullable=False),
    sa.Column('IDCarroceria', sa.Integer(), nullable=False),
    sa.Column('Patente', sa.String(length=10), nullable=False),
    sa.Column('Linea', sa.String(length=5), nullable=True),
    sa.Column('Interno', sa.String(length=7), nullable=True),
    sa.Column('Asientos', sa.Integer(), nullable=True),
    sa.Column('AñoCNRT', sa.Integer(), nullable=True),
    sa.Column('FechaAlta', sa.Date(), nullable=True),
    sa.Column('Estado', sa.String(length=25), nullable=False),
    sa.ForeignKeyConstraint(['IDCarroceria'], ['CARROCERIA.IDCarroceria'], ),
    sa.ForeignKeyConstraint(['IDChasis'], ['CHASIS.IDChasis'], ),
    sa.ForeignKeyConstraint(['IDMotor'], ['MOTOR.IDMotor'], ),
    sa.PrimaryKeyConstraint('IDParqueMovil'),
    sa.UniqueConstraint('IDChasis'),
    sa.UniqueConstraint('IDMotor'),
    sa.UniqueConstraint('Patente')
    )
    op.create_table('PARQUE_MOVIL_HISTORIAL',
    sa.Column('IDParqueHistorial', sa.Integer(), nullable=False),
    sa.Column('IDParqueMovil', sa.Integer(), nullable=False),
    sa.Column('IDChasis', sa.Integer(), nullable=False),
    sa.Column('IDMotor', sa.Integer(), nullable=False),
    sa.Column('IDCarroceria', sa.Integer(), nullable=False),
    sa.Column('FechaHistorial', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('Patente', sa.String(length=10), nullable=False),
    sa.Column('Linea', sa.String(length=5), nullable=True),
    sa.Column('Interno', sa.String(length=7), nullable=True),
    sa.Column('Estado', sa.String(length=25), nullable=False),
    sa.Column('Motivo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['IDParqueMovil'], ['PARQUE_MOVIL.IDParqueMovil'], ),
    sa.PrimaryKeyConstraint('IDParqueHistorial')
    )
    op.create_table('REGISTRO_KM',
    sa.Column('IDRegistroKM', sa.Integer(), nullable=False),
    sa.Column('IDParqueMovil', sa.Integer(), nullable=False),
    sa.Column('FechaLectura', sa.Date(), nullable=False),
    sa.Column('KMTotal', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['IDParqueMovil'], ['PARQUE_MOVIL.IDParqueMovil'], ),
    sa.PrimaryKeyConstraint('IDRegistroKM')
    )
    with op.batch_alter_table('CONSUMO_COMPARACION', schema=None) as batch_op:
        batch_op.alter_column('Consumo',
               existing_type=sa.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('Gasto',
               existing_type=sa.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('CONSUMO_DESVIACION_INDICES', schema=None) as batch_op:
        batch_op.alter_column('MediaRepuesto',
               existing_type=sa.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('MediaDeMediasRepuesto',
               existing_type=sa.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('DiferenciaRepuesto',
               existing_type=sa.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('DesviacionRepuesto',
               existing_type=sa.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('MediaCabecera',
               existing_type=sa.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('MediaDeMediasCabecera',
               existing_type=sa.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('DiferenciaCabecera',
               existing_type=sa.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('DesviacionCabecera',
               existing_type=sa.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('CONSUMO_HISTORIAL', schema=None) as batch_op:
        batch_op.alter_column('TotalConsumo',
               existing_type=sa.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('CONSUMO_INDICE', schema=None) as batch_op:
        batch_op.alter_column('TotalConsumo',
               existing_type=sa.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('TotalCoste',
               existing_type=sa.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('IndiceConsumo',
               existing_type=sa.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('CONTEO_STOCK', schema=None) as batch_op:
        batch_op.alter_column('Reconteos',
               existing_type=sa.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('Precio',
               existing_type=sa.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('DiferenciaStock',
               existing_type=sa.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('DiferenciaPrecio',
               existing_type=sa.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('PrecioAnterior',
               existing_type=sa.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('PrecioActual',
               existing_type=sa.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('Ajuste',
               existing_type=sa.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('StockNuevo',
               existing_type=sa.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('DISTRIBUCION_NORMAL', schema=None) as batch_op:
        batch_op.alter_column('Años',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('AñoPromedio',
               existing_type=sa.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('DesviacionEstandar',
               existing_type=sa.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('DURACION_REPUESTOS', schema=None) as batch_op:
        batch_op.alter_column('DuracionEnMeses',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('DuracionEnAños',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('AñoPromedio',
               existing_type=sa.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('DesviacionEstandar',
               existing_type=sa.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('GOMERIA_DIFERENCIA_MOV_DEP', schema=None) as batch_op:
        batch_op.alter_column('CostoTotal2024',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('CostoTotal2025',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('DiferenciaDeCostos',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('MAXIMOS_MINIMOS', schema=None) as batch_op:
        batch_op.alter_column('Minimo',
               existing_type=sa.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('Maximo',
               existing_type=sa.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('MAXIMOS_MINIMOS', schema=None) as batch_op:
        batch_op.alter_column('Maximo',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('Minimo',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('GOMERIA_DIFERENCIA_MOV_DEP', schema=None) as batch_op:
        batch_op.alter_column('DiferenciaDeCostos',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('CostoTotal2025',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('CostoTotal2024',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('DURACION_REPUESTOS', schema=None) as batch_op:
        batch_op.alter_column('DesviacionEstandar',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('AñoPromedio',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('DuracionEnAños',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('DuracionEnMeses',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('DISTRIBUCION_NORMAL', schema=None) as batch_op:
        batch_op.alter_column('DesviacionEstandar',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('AñoPromedio',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('Años',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('CONTEO_STOCK', schema=None) as batch_op:
        batch_op.alter_column('StockNuevo',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('Ajuste',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('PrecioActual',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('PrecioAnterior',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('DiferenciaPrecio',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('DiferenciaStock',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('Precio',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('Reconteos',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('CONSUMO_INDICE', schema=None) as batch_op:
        batch_op.alter_column('IndiceConsumo',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('TotalCoste',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('TotalConsumo',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('CONSUMO_HISTORIAL', schema=None) as batch_op:
        batch_op.alter_column('TotalConsumo',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('CONSUMO_DESVIACION_INDICES', schema=None) as batch_op:
        batch_op.alter_column('DesviacionCabecera',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('DiferenciaCabecera',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('MediaDeMediasCabecera',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('MediaCabecera',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('DesviacionRepuesto',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('DiferenciaRepuesto',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('MediaDeMediasRepuesto',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('MediaRepuesto',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('CONSUMO_COMPARACION', schema=None) as batch_op:
        batch_op.alter_column('Gasto',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('Consumo',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    op.drop_table('REGISTRO_KM')
    op.drop_table('PARQUE_MOVIL_HISTORIAL')
    op.drop_table('PARQUE_MOVIL')
    op.drop_table('MOTOR')
    op.drop_table('CHASIS')
    op.drop_table('MOTOR_MODELO')
    op.drop_table('CHASIS_MODELO')
    op.drop_table('MOTOR_MARCA')
    op.drop_table('CHASIS_MARCA')
    op.drop_table('CARROCERIA')
    # ### end Alembic commands ###
