"""cambio duracion y distribucion repuestos

Revision ID: 64815f746bd3
Revises: 99ead0bacba9
Create Date: 2026-06-25 11:25:53.725874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64815f746bd3'
down_revision: Union[str, Sequence[str], None] = '99ead0bacba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('DISTRIBUCION_NORMAL', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_DISTRIBUCION_NORMAL_Cabecera'))
        batch_op.drop_column('Cabecera')

    with op.batch_alter_table('DURACION_REPUESTOS', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_DURACION_REPUESTOS_Cabecera'))
        batch_op.drop_column('Cabecera')
        batch_op.drop_column('Observaciones')

    with op.batch_alter_table('PARQUE_MOVIL', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Fecha0KM', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PARQUE_MOVIL', schema=None) as batch_op:
        batch_op.drop_column('Fecha0KM')

    with op.batch_alter_table('DURACION_REPUESTOS', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Observaciones', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('Cabecera', sa.VARCHAR(), nullable=True))
        batch_op.create_index(batch_op.f('ix_DURACION_REPUESTOS_Cabecera'), ['Cabecera'], unique=False)

    with op.batch_alter_table('DISTRIBUCION_NORMAL', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Cabecera', sa.VARCHAR(), nullable=True))
        batch_op.create_index(batch_op.f('ix_DISTRIBUCION_NORMAL_Cabecera'), ['Cabecera'], unique=False)

    # ### end Alembic commands ###
