"""creacion de la tabla USUARIOS_CODIGOS

Revision ID: 793fb315a3cb
Revises: 91cc1b355cf4
Create Date: 2026-03-13 09:18:37.831695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '793fb315a3cb'
down_revision: Union[str, Sequence[str], None] = '91cc1b355cf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('USUARIOS_CODIGOS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.Column('UsuariosAntiguos', sa.String(length=5), nullable=False),
    sa.Column('UsuariosNuevos', sa.String(length=5), nullable=True),
    sa.Column('NombresAntiguos', sa.String(), nullable=False),
    sa.Column('NombresNuevos', sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('USUARIOS_CODIGOS')
    # ### end Alembic commands ###
