"""Agregado de repuestos_codigos y proveedores

Revision ID: 8651db023d52
Revises: 793fb315a3cb
Create Date: 2026-04-21 09:24:32.514435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8651db023d52'
down_revision: Union[str, Sequence[str], None] = '793fb315a3cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PROVEEDORES',
    sa.Column('NroProv', sa.Integer(), nullable=False),
    sa.Column('RazonSocial', sa.String(), nullable=False),
    sa.Column('CUIT', sa.String(length=13), nullable=False),
    sa.Column('Localidad', sa.String(), nullable=True),
    sa.Column('Mail', sa.String(), nullable=True),
    sa.Column('Telefono', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('NroProv')
    )
    op.create_table('REPUESTOS_CODIGOS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Descripcion', sa.String(), nullable=False),
    sa.Column('Deposito', sa.String(length=10), nullable=False),
    sa.Column('Familia', sa.Integer(), nullable=False),
    sa.Column('Articulo', sa.Integer(), nullable=False),
    sa.Column('Codigos', sa.String(length=10), nullable=False),
    sa.Column('CodigosConCero', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('REPUESTOS_CODIGOS')
    op.drop_table('PROVEEDORES')
    # ### end Alembic commands ###
