"""agregado de base repuesto

Revision ID: 91cc1b355cf4
Revises: 10c5ad27cc5e
Create Date: 2026-02-27 15:09:35.276613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91cc1b355cf4'
down_revision: Union[str, Sequence[str], None] = '10c5ad27cc5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CONSUMO_COMPARACION', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_CONSUMO_COMPARACION_Cabecera'), ['Cabecera'], unique=False)
        batch_op.create_index(batch_op.f('ix_CONSUMO_COMPARACION_Repuesto'), ['Repuesto'], unique=False)

    with op.batch_alter_table('CONSUMO_INDICE', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_CONSUMO_INDICE_Repuesto'), ['Repuesto'], unique=False)

    with op.batch_alter_table('CONSUMO_OBLIGATORIO', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_CONSUMO_OBLIGATORIO_Repuesto'), ['Repuesto'], unique=False)

    with op.batch_alter_table('CONSUMO_PREVISION', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_CONSUMO_PREVISION_Repuesto'), ['Repuesto'], unique=False)

    with op.batch_alter_table('CONSUMO_PREVISION_DATA', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_CONSUMO_PREVISION_DATA_Repuesto'), ['Repuesto'], unique=False)

    with op.batch_alter_table('DISTRIBUCION_NORMAL', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_DISTRIBUCION_NORMAL_Cabecera'), ['Cabecera'], unique=False)
        batch_op.create_index(batch_op.f('ix_DISTRIBUCION_NORMAL_Repuesto'), ['Repuesto'], unique=False)

    with op.batch_alter_table('DURACION_REPUESTOS', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_DURACION_REPUESTOS_Cabecera'), ['Cabecera'], unique=False)
        batch_op.create_index(batch_op.f('ix_DURACION_REPUESTOS_Repuesto'), ['Repuesto'], unique=False)

    with op.batch_alter_table('GARANTIAS_CONSUMO', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_GARANTIAS_CONSUMO_Repuesto'), ['Repuesto'], unique=False)

    with op.batch_alter_table('GARANTIAS_DATOS', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_GARANTIAS_DATOS_Cabecera'), ['Cabecera'], unique=False)
        batch_op.create_index(batch_op.f('ix_GARANTIAS_DATOS_Repuesto'), ['Repuesto'], unique=False)

    with op.batch_alter_table('GARANTIAS_FALLA', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_GARANTIAS_FALLA_Repuesto'), ['Repuesto'], unique=False)

    with op.batch_alter_table('GOMERIA_DIFERENCIA_MOV_DEP', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_GOMERIA_DIFERENCIA_MOV_DEP_Repuesto'), ['Repuesto'], unique=False)

    with op.batch_alter_table('GOMERIA_TRANSFERENCIAS_DEP', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_GOMERIA_TRANSFERENCIAS_DEP_Cabecera'), ['Cabecera'], unique=False)
        batch_op.create_index(batch_op.f('ix_GOMERIA_TRANSFERENCIAS_DEP_Repuesto'), ['Repuesto'], unique=False)

    with op.batch_alter_table('MAXIMOS_MINIMOS', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_MAXIMOS_MINIMOS_Repuesto'), ['Repuesto'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('MAXIMOS_MINIMOS', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_MAXIMOS_MINIMOS_Repuesto'))

    with op.batch_alter_table('GOMERIA_TRANSFERENCIAS_DEP', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_GOMERIA_TRANSFERENCIAS_DEP_Repuesto'))
        batch_op.drop_index(batch_op.f('ix_GOMERIA_TRANSFERENCIAS_DEP_Cabecera'))

    with op.batch_alter_table('GOMERIA_DIFERENCIA_MOV_DEP', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_GOMERIA_DIFERENCIA_MOV_DEP_Repuesto'))

    with op.batch_alter_table('GARANTIAS_FALLA', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_GARANTIAS_FALLA_Repuesto'))

    with op.batch_alter_table('GARANTIAS_DATOS', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_GARANTIAS_DATOS_Repuesto'))
        batch_op.drop_index(batch_op.f('ix_GARANTIAS_DATOS_Cabecera'))

    with op.batch_alter_table('GARANTIAS_CONSUMO', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_GARANTIAS_CONSUMO_Repuesto'))

    with op.batch_alter_table('DURACION_REPUESTOS', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_DURACION_REPUESTOS_Repuesto'))
        batch_op.drop_index(batch_op.f('ix_DURACION_REPUESTOS_Cabecera'))

    with op.batch_alter_table('DISTRIBUCION_NORMAL', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_DISTRIBUCION_NORMAL_Repuesto'))
        batch_op.drop_index(batch_op.f('ix_DISTRIBUCION_NORMAL_Cabecera'))

    with op.batch_alter_table('CONSUMO_PREVISION_DATA', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_CONSUMO_PREVISION_DATA_Repuesto'))

    with op.batch_alter_table('CONSUMO_PREVISION', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_CONSUMO_PREVISION_Repuesto'))

    with op.batch_alter_table('CONSUMO_OBLIGATORIO', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_CONSUMO_OBLIGATORIO_Repuesto'))

    with op.batch_alter_table('CONSUMO_INDICE', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_CONSUMO_INDICE_Repuesto'))

    with op.batch_alter_table('CONSUMO_COMPARACION', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_CONSUMO_COMPARACION_Repuesto'))
        batch_op.drop_index(batch_op.f('ix_CONSUMO_COMPARACION_Cabecera'))

    # ### end Alembic commands ###
