"""fix: cuit proveedores ahora puede ser nulo

Revision ID: 99ead0bacba9
Revises: 8651db023d52
Create Date: 2026-04-21 09:57:36.502418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99ead0bacba9'
down_revision: Union[str, Sequence[str], None] = '8651db023d52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PROVEEDORES', schema=None) as batch_op:
        batch_op.alter_column('CUIT',
               existing_type=sa.VARCHAR(length=13),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PROVEEDORES', schema=None) as batch_op:
        batch_op.alter_column('CUIT',
               existing_type=sa.VARCHAR(length=13),
               nullable=False)

    # ### end Alembic commands ###
