"""drop de tablas sin usar

Revision ID: c6f12c8b5c8b
Revises: 
Create Date: 2026-02-27 13:58:37.339472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6f12c8b5c8b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MOTOR')
    op.drop_table('INTERNOS_CABECERA')
    op.drop_table('MOTORES_CABECERA')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MOTORES_CABECERA',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('Cabecera', sa.VARCHAR(), nullable=True),
    sa.Column('CantidadMotores', sa.INTEGER(), nullable=True),
    sa.Column('MotorID', sa.INTEGER(), nullable=True)
    )
    op.create_table('INTERNOS_CABECERA',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('Linea', sa.INTEGER(), nullable=True),
    sa.Column('Interno', sa.INTEGER(), nullable=True),
    sa.Column('Dominio', sa.VARCHAR(), nullable=True),
    sa.Column('ChasisNum', sa.VARCHAR(), nullable=True),
    sa.Column('ChasisAño', sa.INTEGER(), nullable=True),
    sa.Column('MotorNumSerie', sa.INTEGER(), nullable=True),
    sa.Column('Cabecera', sa.VARCHAR(), nullable=True),
    sa.Column('MotorID', sa.INTEGER(), nullable=True)
    )
    op.create_table('MOTOR',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('Marca', sa.VARCHAR(), nullable=True),
    sa.Column('Modelo', sa.VARCHAR(), nullable=True),
    sa.Column('Normativa', sa.VARCHAR(), nullable=True),
    sa.Column('Chasis', sa.VARCHAR(), nullable=True),
    sa.Column('Cilindros', sa.VARCHAR(), nullable=True)
    )
    # ### end Alembic commands ###
