"""nueva_tabla_gomeria

Revision ID: ed4f29ece522
Revises: 2551e9cd0e4b
Create Date: 2026-07-08 11:47:30.069590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed4f29ece522'
down_revision: Union[str, Sequence[str], None] = '2551e9cd0e4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats_gomeria_movimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Codigo', sa.String(length=9), nullable=False),
    sa.Column('Repuesto', sa.String(length=150), nullable=False),
    sa.Column('Año', sa.Integer(), nullable=False),
    sa.Column('ConsumoTotal', sa.Integer(), nullable=False),
    sa.Column('CostoTotal', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stats_gomeria_movimientos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stats_gomeria_movimientos_Codigo'), ['Codigo'], unique=False)

    with op.batch_alter_table('data_coches_cabecera', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_COCHES_CABECERA_Cabecera'))
        batch_op.create_index(batch_op.f('ix_data_coches_cabecera_Cabecera'), ['Cabecera'], unique=False)

    with op.batch_alter_table('data_maximos_minimos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_MAXIMOS_MINIMOS_Repuesto'))
        batch_op.create_index(batch_op.f('ix_data_maximos_minimos_Repuesto'), ['Repuesto'], unique=False)

    with op.batch_alter_table('stats_consumo_comparacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_CONSUMO_COMPARACION_Cabecera'))
        batch_op.drop_index(batch_op.f('ix_CONSUMO_COMPARACION_Repuesto'))
        batch_op.create_index(batch_op.f('ix_stats_consumo_comparacion_Cabecera'), ['Cabecera'], unique=False)
        batch_op.create_index(batch_op.f('ix_stats_consumo_comparacion_Repuesto'), ['Repuesto'], unique=False)

    with op.batch_alter_table('stats_consumo_desviacion_indices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_CONSUMO_DESVIACION_INDICES_Cabecera'))
        batch_op.create_index(batch_op.f('ix_stats_consumo_desviacion_indices_Cabecera'), ['Cabecera'], unique=False)

    with op.batch_alter_table('stats_consumo_distribucion_normal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_DISTRIBUCION_NORMAL_Repuesto'))
        batch_op.create_index(batch_op.f('ix_stats_consumo_distribucion_normal_Repuesto'), ['Repuesto'], unique=False)

    with op.batch_alter_table('stats_consumo_duracion_repuestos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_DURACION_REPUESTOS_Repuesto'))
        batch_op.create_index(batch_op.f('ix_stats_consumo_duracion_repuestos_Repuesto'), ['Repuesto'], unique=False)

    with op.batch_alter_table('stats_consumo_indice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_CONSUMO_INDICE_Cabecera'))
        batch_op.drop_index(batch_op.f('ix_CONSUMO_INDICE_Repuesto'))
        batch_op.create_index(batch_op.f('ix_stats_consumo_indice_Cabecera'), ['Cabecera'], unique=False)
        batch_op.create_index(batch_op.f('ix_stats_consumo_indice_Repuesto'), ['Repuesto'], unique=False)

    with op.batch_alter_table('stats_consumo_obligatorio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_CONSUMO_OBLIGATORIO_Cabecera'))
        batch_op.drop_index(batch_op.f('ix_CONSUMO_OBLIGATORIO_Repuesto'))
        batch_op.create_index(batch_op.f('ix_stats_consumo_obligatorio_Cabecera'), ['Cabecera'], unique=False)
        batch_op.create_index(batch_op.f('ix_stats_consumo_obligatorio_Repuesto'), ['Repuesto'], unique=False)

    with op.batch_alter_table('stats_consumo_prevision', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_CONSUMO_PREVISION_Repuesto'))
        batch_op.create_index(batch_op.f('ix_stats_consumo_prevision_Repuesto'), ['Repuesto'], unique=False)

    with op.batch_alter_table('stats_consumo_prevision_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_CONSUMO_PREVISION_DATA_Repuesto'))
        batch_op.create_index(batch_op.f('ix_stats_consumo_prevision_data_Repuesto'), ['Repuesto'], unique=False)

    with op.batch_alter_table('stats_garantias_consumo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_GARANTIAS_CONSUMO_Cabecera'))
        batch_op.drop_index(batch_op.f('ix_GARANTIAS_CONSUMO_Repuesto'))
        batch_op.create_index(batch_op.f('ix_stats_garantias_consumo_Cabecera'), ['Cabecera'], unique=False)
        batch_op.create_index(batch_op.f('ix_stats_garantias_consumo_Repuesto'), ['Repuesto'], unique=False)

    with op.batch_alter_table('stats_garantias_datos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_GARANTIAS_DATOS_Cabecera'))
        batch_op.drop_index(batch_op.f('ix_GARANTIAS_DATOS_Repuesto'))
        batch_op.create_index(batch_op.f('ix_stats_garantias_datos_Cabecera'), ['Cabecera'], unique=False)
        batch_op.create_index(batch_op.f('ix_stats_garantias_datos_Repuesto'), ['Repuesto'], unique=False)

    with op.batch_alter_table('stats_garantias_falla', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_GARANTIAS_FALLA_Cabecera'))
        batch_op.drop_index(batch_op.f('ix_GARANTIAS_FALLA_Repuesto'))
        batch_op.create_index(batch_op.f('ix_stats_garantias_falla_Cabecera'), ['Cabecera'], unique=False)
        batch_op.create_index(batch_op.f('ix_stats_garantias_falla_Repuesto'), ['Repuesto'], unique=False)

    with op.batch_alter_table('stats_gomeria_diferencia_mov_rep', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_GOMERIA_DIFERENCIA_MOV_DEP_Repuesto'))
        batch_op.create_index(batch_op.f('ix_stats_gomeria_diferencia_mov_rep_Repuesto'), ['Repuesto'], unique=False)

    with op.batch_alter_table('stats_gomeria_transferencias_dep', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_GOMERIA_TRANSFERENCIAS_DEP_Cabecera'))
        batch_op.drop_index(batch_op.f('ix_GOMERIA_TRANSFERENCIAS_DEP_Repuesto'))
        batch_op.create_index(batch_op.f('ix_stats_gomeria_transferencias_dep_Cabecera'), ['Cabecera'], unique=False)
        batch_op.create_index(batch_op.f('ix_stats_gomeria_transferencias_dep_Repuesto'), ['Repuesto'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stats_gomeria_transferencias_dep', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stats_gomeria_transferencias_dep_Repuesto'))
        batch_op.drop_index(batch_op.f('ix_stats_gomeria_transferencias_dep_Cabecera'))
        batch_op.create_index(batch_op.f('ix_GOMERIA_TRANSFERENCIAS_DEP_Repuesto'), ['Repuesto'], unique=False)
        batch_op.create_index(batch_op.f('ix_GOMERIA_TRANSFERENCIAS_DEP_Cabecera'), ['Cabecera'], unique=False)

    with op.batch_alter_table('stats_gomeria_diferencia_mov_rep', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stats_gomeria_diferencia_mov_rep_Repuesto'))
        batch_op.create_index(batch_op.f('ix_GOMERIA_DIFERENCIA_MOV_DEP_Repuesto'), ['Repuesto'], unique=False)

    with op.batch_alter_table('stats_garantias_falla', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stats_garantias_falla_Repuesto'))
        batch_op.drop_index(batch_op.f('ix_stats_garantias_falla_Cabecera'))
        batch_op.create_index(batch_op.f('ix_GARANTIAS_FALLA_Repuesto'), ['Repuesto'], unique=False)
        batch_op.create_index(batch_op.f('ix_GARANTIAS_FALLA_Cabecera'), ['Cabecera'], unique=False)

    with op.batch_alter_table('stats_garantias_datos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stats_garantias_datos_Repuesto'))
        batch_op.drop_index(batch_op.f('ix_stats_garantias_datos_Cabecera'))
        batch_op.create_index(batch_op.f('ix_GARANTIAS_DATOS_Repuesto'), ['Repuesto'], unique=False)
        batch_op.create_index(batch_op.f('ix_GARANTIAS_DATOS_Cabecera'), ['Cabecera'], unique=False)

    with op.batch_alter_table('stats_garantias_consumo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stats_garantias_consumo_Repuesto'))
        batch_op.drop_index(batch_op.f('ix_stats_garantias_consumo_Cabecera'))
        batch_op.create_index(batch_op.f('ix_GARANTIAS_CONSUMO_Repuesto'), ['Repuesto'], unique=False)
        batch_op.create_index(batch_op.f('ix_GARANTIAS_CONSUMO_Cabecera'), ['Cabecera'], unique=False)

    with op.batch_alter_table('stats_consumo_prevision_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stats_consumo_prevision_data_Repuesto'))
        batch_op.create_index(batch_op.f('ix_CONSUMO_PREVISION_DATA_Repuesto'), ['Repuesto'], unique=False)

    with op.batch_alter_table('stats_consumo_prevision', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stats_consumo_prevision_Repuesto'))
        batch_op.create_index(batch_op.f('ix_CONSUMO_PREVISION_Repuesto'), ['Repuesto'], unique=False)

    with op.batch_alter_table('stats_consumo_obligatorio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stats_consumo_obligatorio_Repuesto'))
        batch_op.drop_index(batch_op.f('ix_stats_consumo_obligatorio_Cabecera'))
        batch_op.create_index(batch_op.f('ix_CONSUMO_OBLIGATORIO_Repuesto'), ['Repuesto'], unique=False)
        batch_op.create_index(batch_op.f('ix_CONSUMO_OBLIGATORIO_Cabecera'), ['Cabecera'], unique=False)

    with op.batch_alter_table('stats_consumo_indice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stats_consumo_indice_Repuesto'))
        batch_op.drop_index(batch_op.f('ix_stats_consumo_indice_Cabecera'))
        batch_op.create_index(batch_op.f('ix_CONSUMO_INDICE_Repuesto'), ['Repuesto'], unique=False)
        batch_op.create_index(batch_op.f('ix_CONSUMO_INDICE_Cabecera'), ['Cabecera'], unique=False)

    with op.batch_alter_table('stats_consumo_duracion_repuestos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stats_consumo_duracion_repuestos_Repuesto'))
        batch_op.create_index(batch_op.f('ix_DURACION_REPUESTOS_Repuesto'), ['Repuesto'], unique=False)

    with op.batch_alter_table('stats_consumo_distribucion_normal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stats_consumo_distribucion_normal_Repuesto'))
        batch_op.create_index(batch_op.f('ix_DISTRIBUCION_NORMAL_Repuesto'), ['Repuesto'], unique=False)

    with op.batch_alter_table('stats_consumo_desviacion_indices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stats_consumo_desviacion_indices_Cabecera'))
        batch_op.create_index(batch_op.f('ix_CONSUMO_DESVIACION_INDICES_Cabecera'), ['Cabecera'], unique=False)

    with op.batch_alter_table('stats_consumo_comparacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stats_consumo_comparacion_Repuesto'))
        batch_op.drop_index(batch_op.f('ix_stats_consumo_comparacion_Cabecera'))
        batch_op.create_index(batch_op.f('ix_CONSUMO_COMPARACION_Repuesto'), ['Repuesto'], unique=False)
        batch_op.create_index(batch_op.f('ix_CONSUMO_COMPARACION_Cabecera'), ['Cabecera'], unique=False)

    with op.batch_alter_table('data_maximos_minimos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_maximos_minimos_Repuesto'))
        batch_op.create_index(batch_op.f('ix_MAXIMOS_MINIMOS_Repuesto'), ['Repuesto'], unique=False)

    with op.batch_alter_table('data_coches_cabecera', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_coches_cabecera_Cabecera'))
        batch_op.create_index(batch_op.f('ix_COCHES_CABECERA_Cabecera'), ['Cabecera'], unique=False)

    with op.batch_alter_table('stats_gomeria_movimientos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stats_gomeria_movimientos_Codigo'))

    op.drop_table('stats_gomeria_movimientos')
    # ### end Alembic commands ###
