"""add: parque movil a postgres

Revision ID: f898987ebaa9
Revises: 
Create Date: 2026-07-03 09:40:36.600561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f898987ebaa9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CARROCERIA',
    sa.Column('IDCarroceria', sa.Integer(), nullable=False),
    sa.Column('Marca', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('IDCarroceria'),
    schema='datos'
    )
    op.create_table('CHASIS_MARCA',
    sa.Column('IDChasisMarca', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('IDChasisMarca'),
    sa.UniqueConstraint('Nombre'),
    schema='datos'
    )
    op.create_table('MOTOR_MARCA',
    sa.Column('IDMotorMarca', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('IDMotorMarca'),
    sa.UniqueConstraint('Nombre'),
    schema='datos'
    )
    op.create_table('CHASIS_MODELO',
    sa.Column('IDChasisModelo', sa.Integer(), nullable=False),
    sa.Column('IDChasisMarca', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['IDChasisMarca'], ['datos.CHASIS_MARCA.IDChasisMarca'], ),
    sa.PrimaryKeyConstraint('IDChasisModelo'),
    sa.UniqueConstraint('IDChasisMarca', 'Nombre', name='unique_chasis_marca_modelo'),
    schema='datos'
    )
    op.create_table('MOTOR_MODELO',
    sa.Column('IDMotorModelo', sa.Integer(), nullable=False),
    sa.Column('IDMotorMarca', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['IDMotorMarca'], ['datos.MOTOR_MARCA.IDMotorMarca'], ),
    sa.PrimaryKeyConstraint('IDMotorModelo'),
    sa.UniqueConstraint('IDMotorMarca', 'Nombre', name='unique_motor_marca_modelo'),
    schema='datos'
    )
    op.create_table('CHASIS',
    sa.Column('IDChasis', sa.Integer(), nullable=False),
    sa.Column('IDChasisModelo', sa.Integer(), nullable=False),
    sa.Column('ChasisCodigo', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['IDChasisModelo'], ['datos.CHASIS_MODELO.IDChasisModelo'], ),
    sa.PrimaryKeyConstraint('IDChasis'),
    sa.UniqueConstraint('ChasisCodigo'),
    schema='datos'
    )
    op.create_table('MOTOR',
    sa.Column('IDMotor', sa.Integer(), nullable=False),
    sa.Column('IDMotorModelo', sa.Integer(), nullable=False),
    sa.Column('MotorCodigo', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['IDMotorModelo'], ['datos.MOTOR_MODELO.IDMotorModelo'], ),
    sa.PrimaryKeyConstraint('IDMotor'),
    sa.UniqueConstraint('MotorCodigo'),
    schema='datos'
    )
    op.create_table('PARQUE_MOVIL',
    sa.Column('IDParqueMovil', sa.Integer(), nullable=False),
    sa.Column('IDChasis', sa.Integer(), nullable=False),
    sa.Column('IDMotor', sa.Integer(), nullable=False),
    sa.Column('IDCarroceria', sa.Integer(), nullable=False),
    sa.Column('Patente', sa.String(length=10), nullable=False),
    sa.Column('Linea', sa.String(length=5), nullable=True),
    sa.Column('Interno', sa.String(length=7), nullable=True),
    sa.Column('Asientos', sa.Integer(), nullable=True),
    sa.Column('AñoCNRT', sa.Integer(), nullable=True),
    sa.Column('FechaAlta', sa.Date(), nullable=True),
    sa.Column('Estado', sa.String(length=25), nullable=False),
    sa.ForeignKeyConstraint(['IDCarroceria'], ['datos.CARROCERIA.IDCarroceria'], ),
    sa.ForeignKeyConstraint(['IDChasis'], ['datos.CHASIS.IDChasis'], ),
    sa.ForeignKeyConstraint(['IDMotor'], ['datos.MOTOR.IDMotor'], ),
    sa.PrimaryKeyConstraint('IDParqueMovil'),
    sa.UniqueConstraint('IDChasis'),
    sa.UniqueConstraint('IDMotor'),
    sa.UniqueConstraint('Patente'),
    schema='datos'
    )
    op.create_table('PARQUE_MOVIL_HISTORIAL',
    sa.Column('IDParqueHistorial', sa.Integer(), nullable=False),
    sa.Column('IDParqueMovil', sa.Integer(), nullable=False),
    sa.Column('IDChasis', sa.Integer(), nullable=False),
    sa.Column('IDMotor', sa.Integer(), nullable=False),
    sa.Column('IDCarroceria', sa.Integer(), nullable=False),
    sa.Column('FechaHistorial', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('Patente', sa.String(length=10), nullable=False),
    sa.Column('Linea', sa.String(length=5), nullable=True),
    sa.Column('Interno', sa.String(length=7), nullable=True),
    sa.Column('Estado', sa.String(length=25), nullable=False),
    sa.Column('Motivo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['IDParqueMovil'], ['datos.PARQUE_MOVIL.IDParqueMovil'], ),
    sa.PrimaryKeyConstraint('IDParqueHistorial'),
    schema='datos'
    )
    op.create_table('REGISTRO_KM',
    sa.Column('IDRegistroKM', sa.Integer(), nullable=False),
    sa.Column('IDParqueMovil', sa.Integer(), nullable=False),
    sa.Column('FechaLectura', sa.Date(), nullable=False),
    sa.Column('KMTotal', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['IDParqueMovil'], ['datos.PARQUE_MOVIL.IDParqueMovil'], ),
    sa.PrimaryKeyConstraint('IDRegistroKM'),
    schema='datos'
    )
    op.execute('DROP TABLE estadisticas."PARQUE_MOVIL_HISTORIAL" CASCADE')
    op.execute('DROP TABLE estadisticas."MOTOR_MODELO" CASCADE')
    op.execute('DROP TABLE estadisticas."MOTOR" CASCADE')
    op.execute('DROP TABLE estadisticas."MOTOR_MARCA" CASCADE')
    op.execute('DROP TABLE estadisticas."REGISTRO_KM" CASCADE')
    op.execute('DROP TABLE estadisticas."CHASIS_MODELO" CASCADE')
    op.execute('DROP TABLE estadisticas."PARQUE_MOVIL" CASCADE')
    op.execute('DROP TABLE estadisticas."CHASIS_MARCA" CASCADE')
    op.execute('DROP TABLE estadisticas."CARROCERIA" CASCADE')
    op.execute('DROP TABLE estadisticas."CHASIS" CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CHASIS',
    sa.Column('IDChasis', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('IDChasisModelo', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ChasisCodigo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['IDChasisModelo'], ['estadisticas.CHASIS_MODELO.IDChasisModelo'], name=op.f('CHASIS_IDChasisModelo_fkey')),
    sa.PrimaryKeyConstraint('IDChasis', name=op.f('CHASIS_pkey')),
    sa.UniqueConstraint('ChasisCodigo', name=op.f('CHASIS_ChasisCodigo_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='estadisticas'
    )
    op.create_table('CARROCERIA',
    sa.Column('IDCarroceria', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Marca', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('IDCarroceria', name=op.f('CARROCERIA_pkey')),
    schema='estadisticas'
    )
    op.create_table('CHASIS_MARCA',
    sa.Column('IDChasisMarca', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Nombre', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('IDChasisMarca', name=op.f('CHASIS_MARCA_pkey')),
    sa.UniqueConstraint('Nombre', name=op.f('CHASIS_MARCA_Nombre_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='estadisticas'
    )
    op.create_table('PARQUE_MOVIL',
    sa.Column('IDParqueMovil', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('IDChasis', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('IDMotor', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('IDCarroceria', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Patente', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('Linea', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('Interno', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.Column('Asientos', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('AñoCNRT', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('FechaAlta', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('Estado', sa.VARCHAR(length=25), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['IDCarroceria'], ['estadisticas.CARROCERIA.IDCarroceria'], name=op.f('PARQUE_MOVIL_IDCarroceria_fkey')),
    sa.ForeignKeyConstraint(['IDChasis'], ['estadisticas.CHASIS.IDChasis'], name=op.f('PARQUE_MOVIL_IDChasis_fkey')),
    sa.ForeignKeyConstraint(['IDMotor'], ['estadisticas.MOTOR.IDMotor'], name=op.f('PARQUE_MOVIL_IDMotor_fkey')),
    sa.PrimaryKeyConstraint('IDParqueMovil', name=op.f('PARQUE_MOVIL_pkey')),
    sa.UniqueConstraint('IDChasis', name=op.f('PARQUE_MOVIL_IDChasis_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('IDMotor', name=op.f('PARQUE_MOVIL_IDMotor_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('Patente', name=op.f('PARQUE_MOVIL_Patente_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='estadisticas'
    )
    op.create_table('CHASIS_MODELO',
    sa.Column('IDChasisModelo', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('IDChasisMarca', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Nombre', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['IDChasisMarca'], ['estadisticas.CHASIS_MARCA.IDChasisMarca'], name=op.f('CHASIS_MODELO_IDChasisMarca_fkey')),
    sa.PrimaryKeyConstraint('IDChasisModelo', name=op.f('CHASIS_MODELO_pkey')),
    sa.UniqueConstraint('IDChasisMarca', 'Nombre', name=op.f('unique_chasis_marca_modelo'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='estadisticas'
    )
    op.create_table('REGISTRO_KM',
    sa.Column('IDRegistroKM', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('IDParqueMovil', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('FechaLectura', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('KMTotal', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['IDParqueMovil'], ['estadisticas.PARQUE_MOVIL.IDParqueMovil'], name=op.f('REGISTRO_KM_IDParqueMovil_fkey')),
    sa.PrimaryKeyConstraint('IDRegistroKM', name=op.f('REGISTRO_KM_pkey')),
    schema='estadisticas'
    )
    op.create_table('MOTOR_MARCA',
    sa.Column('IDMotorMarca', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Nombre', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('IDMotorMarca', name=op.f('MOTOR_MARCA_pkey')),
    sa.UniqueConstraint('Nombre', name=op.f('MOTOR_MARCA_Nombre_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='estadisticas'
    )
    op.create_table('MOTOR',
    sa.Column('IDMotor', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('IDMotorModelo', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('MotorCodigo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['IDMotorModelo'], ['estadisticas.MOTOR_MODELO.IDMotorModelo'], name=op.f('MOTOR_IDMotorModelo_fkey')),
    sa.PrimaryKeyConstraint('IDMotor', name=op.f('MOTOR_pkey')),
    sa.UniqueConstraint('MotorCodigo', name=op.f('MOTOR_MotorCodigo_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='estadisticas'
    )
    op.create_table('MOTOR_MODELO',
    sa.Column('IDMotorModelo', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('IDMotorMarca', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Nombre', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['IDMotorMarca'], ['estadisticas.MOTOR_MARCA.IDMotorMarca'], name=op.f('MOTOR_MODELO_IDMotorMarca_fkey')),
    sa.PrimaryKeyConstraint('IDMotorModelo', name=op.f('MOTOR_MODELO_pkey')),
    sa.UniqueConstraint('IDMotorMarca', 'Nombre', name=op.f('unique_motor_marca_modelo'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='estadisticas'
    )
    op.create_table('PARQUE_MOVIL_HISTORIAL',
    sa.Column('IDParqueHistorial', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('IDParqueMovil', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('IDChasis', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('IDMotor', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('IDCarroceria', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('FechaHistorial', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('Patente', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('Linea', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('Interno', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.Column('Estado', sa.VARCHAR(length=25), autoincrement=False, nullable=False),
    sa.Column('Motivo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['IDParqueMovil'], ['estadisticas.PARQUE_MOVIL.IDParqueMovil'], name=op.f('PARQUE_MOVIL_HISTORIAL_IDParqueMovil_fkey')),
    sa.PrimaryKeyConstraint('IDParqueHistorial', name=op.f('PARQUE_MOVIL_HISTORIAL_pkey')),
    schema='estadisticas'
    )
    op.drop_table('REGISTRO_KM', schema='datos')
    op.drop_table('PARQUE_MOVIL_HISTORIAL', schema='datos')
    op.drop_table('PARQUE_MOVIL', schema='datos')
    op.drop_table('MOTOR', schema='datos')
    op.drop_table('CHASIS', schema='datos')
    op.drop_table('MOTOR_MODELO', schema='datos')
    op.drop_table('CHASIS_MODELO', schema='datos')
    op.drop_table('MOTOR_MARCA', schema='datos')
    op.drop_table('CHASIS_MARCA', schema='datos')
    op.drop_table('CARROCERIA', schema='datos')
    # ### end Alembic commands ###
